### ISSUE TITLE
Building an application with cbl, cbl_flutter_ee downloads x86 native executables

### ISSUE THREAD

**Issue by jonahwilliams** [cbl-dart/cbl-dart#437]
An application that includes these cbl libraries will download and bundle an x86 native couchbase library. Flutter does not support the x86 ABI (only x86_64, so this is entirely wasted.

```yaml
name: cbl_example
description: A new Flutter project.

environment:
  sdk: '>=2.18 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cbl: ^2.1.1
  cbl_flutter: ^2.0.2
  cbl_flutter_ee: ^2.1.2
```

`flutter build apk --target-platform=android-arm64 --analyze-size`
`dart devtools --appSizeBase=path/to/output_from_previous_command` (ignore flutter pub global run)

Notice that there is an x86 architecture slice.
