### ISSUE TITLE
Replicator throws exception 

### ISSUE THREAD

**Issue by aliibrahimroshan** [cbl-dart/cbl-dart#477]
Hello,

I when run the replicator it thows exception in cbl_service.dart file. The method return type needs integer but its returning no thing when i run the app it gets crashed . 

i am using   cbl_flutter: ^2.0.6 , cbl_flutter_ee: ^2.1.6 in my pub file

to fix this issue i did some work around which starts the replication process smoothly here is my work around 

```
**//first i added try catch block** 
 try {
      final replicator = await FfiReplicator.create(
        config,
        // The isolate running this service should not be crashed by unhandled
        // errors in the callbacks registered by the client. The client is
        // responsible for reporting those errors as unhandled in its isolate.
        ignoreCallbackErrorsInDart: true,
      );
      return _objectRegistry.addObject(replicator); **// --> removed await from here** 
    } catch (e) {
      // Handle the exception here
      print('An exception occurred creating the replicator: $e');
    }

    return 1; **// <--- then returned integer** 
```

**Comment by aliibrahimroshan** [comment]
```
name: crud_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  dropdown_button2: ^2.1.0
  cbl: ^2.1.8
  cbl_flutter: ^2.0.6
  cbl_flutter_ee: ^2.1.6
  intl: ^0.18.0
  flutter_animator: ^3.2.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


```
my replication method 
```

static Future replicateIniDb() async {
    try {
      final replicator = await Replicator.create(
        ReplicatorConfiguration(
          database: DbConnection.getIniDatabaseInstance!,
          target: UrlEndpoint(
            Uri.parse('ws://localhost:4984/$iniBucket'),
          ),
          continuous: true,
          replicatorType: ReplicatorType.pushAndPull,
          authenticator:
              BasicAuthenticator(username: 'sync', password: 'sync12345'),
          enableAutoPurge: false,
        ),
      );

      await replicator.addChangeListener((change) {
        print('Replicator activity ini db: ${change.status.activity}');
      });

      await replicator.start();
    } catch (e) {
      // Handle the exception here
      print('An exception occurred: $e');
    }
  }
```

Error it throws is 

```
ERROR: ../../.pub-cache/hosted/pub.dev/cbl-2.1.8/lib/src/service/cbl_service.dart:551:15: Error: A non-null value must be returned since the return type 'int' doesn't allow null.
cbl_service.dart:551
ERROR:   Future<int> _createReplicator(CreateReplicator request) async {
ERROR:               ^
ERROR: Target kernel_snapshot failed: Exception
Exception: Build process failed
Exited (sigterm)
```
