### ISSUE TITLE
Windows Application cbl_flutter_ee error {cbl_flutter_install}

### ISSUE THREAD

**Issue by callllqqq** [cbl-dart/cbl-dart#723]
right when i try to build my windows application in flutter when i add the cbl_flutter_ee package i get error in my debug console :  Launching lib\main.dart on Windows in debug mode...
CMake Error at flutter/ephemeral/.plugin_symlinks/cbl_flutter_ee/windows/CMakeLists.txt:28 (message):
  Failed to activate cbl_flutter_install:

  no such file or directory
5

Error: Unable to generate build files
i there a way around this issues ?

**Comment by blaugold** [comment]
Thanks @callllqqq! 

I've applied the fix for https://github.com/cbl-dart/cbl-dart/issues/689 to all other platforms. Could you try it again with the latest commit of the PR (a6b0d37632f856e2598c8ecefe8db062c807cd6f of https://github.com/cbl-dart/cbl-dart/pull/722)?

```yaml
dependency_overrides:
  cbl_flutter_ee:
    git:
      url: https://github.com/cbl-dart/cbl-dart.git
      path: packages/cbl_flutter_ee
      ref: a6b0d37632f856e2598c8ecefe8db062c807cd6f
```
